# Generated by Django 4.2.7 on 2023-11-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0002_alter_thread_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="content",
            field=models.TextField(default="Default Content"),
        ),
    ]
